name = "j-hiplitehehe"
main = "index.js"
compatibility_date = "2024-11-25"

# Uncomment if you use your own domain:
# route = "https://api.yourdomain.com/*"

[[kv_namespaces]]
binding = "TYPE_STORE"
id = "your-kv-namespace-id"  
